line.bot:
  channel-token: 'lY2EkJjMqq39nRYGVmtr88QDGFxQ83nFNiNQgJa22xH945kvEN/c8vJfF48Ij2PtI88p7nImPnRLL3PH6n/V+dFMj+Ah8VLFOnkHfKGGvkYlvtgzdtweT8w1MLxvpjQJZSLQE4x7WeJ5FsgoCWgvIQdB04t89/1O/w1cDnyilFU='
  channel-secret: '90055a0e74a006666c8d8b7cb974514a'
  handler.path: /callback